### ISSUE TITLE
I can't download the file. Problem with the servers?

### ISSUE THREAD

**Issue by ForceerGames** [uup-dump/website#88] opened 2021-06-17 12:47 UTC
When I download the File it just stops downloading.

It drops to 0 B/s - 214 KB of 4.1 MB

I'm downloading Windows 10 with Windows 10 Pro and Enterprise.

After that it says Couldn't Download - Network Issue when I click resume it downloads get.html and deletes it and the download stops again and the cycle might continue.

If wontfix then I will use the more complicated UUPMediaCreator.

**Comment by juzijun233** [comment] 2021-06-17 16:31
I have the same problem, and the website is very slow!

**Comment by abusayed0206** [comment] 2021-06-18 03:11
This website was down for some hours. But, download server is ok! You just need to click enter on running CMD or close and restart the download process. The previously downloaded file will be merged with the new request.

**Comment by ForceerGames** [comment] 2021-06-18 12:05
Somebody should close this now if it's completely fixed.

**Comment by luzeagithub** [comment] 2021-06-18 15:25
issue is resolved

**Closed by luzeagithub** 2021-06-18 15:25 UTC

**Comment by Azar2477** [comment] 2022-01-04 09:37
The issue is back again.
